export type ServiceDef = {
  slug: string
  category: string           // matches profile.categories[]
  title: string
  headline: string
  subheadline: string
  gradient: string
  accentColor: string
  accentBg: string
  emoji: string
  included: string[]
  notIncluded?: string[]
  priceMin: number
  priceMax: number
  priceUnit: string
  steps: { title: string; desc: string }[]
  faqs: { q: string; a: string }[]
  relatedSlugs: string[]
}

export const SERVICES: ServiceDef[] = [
  {
    slug: 'cleaning',
    category: 'Cleaning',
    title: 'House Cleaning',
    headline: 'A spotless home — without lifting a finger',
    subheadline: 'Book a trusted, verified cleaner in minutes. Flexible scheduling, eco-friendly options, and satisfaction guaranteed.',
    gradient: 'linear-gradient(135deg,#1E3A8A,#38BDF8)',
    accentColor: '#16A34A',
    accentBg: '#F0FDF4',
    emoji: '🧹',
    included: ['Vacuuming & mopping all floors', 'Kitchen surfaces & appliance exteriors', 'Bathroom scrubbing & disinfecting', 'Dusting furniture & shelves', 'Bin emptying & liner replacement', 'Window sills & skirting boards', 'Deep clean add-ons available'],
    notIncluded: ['Inside oven / fridge (add-on)', 'Laundry (add-on)', 'Exterior windows'],
    priceMin: 250, priceMax: 500, priceUnit: 'per session',
    steps: [
      { title: 'Describe your home', desc: 'Tell us the size, frequency, and any special requirements.' },
      { title: 'Choose your cleaner', desc: 'Browse verified, rated cleaners in your area and pick one you like.' },
      { title: 'Relax', desc: 'Your cleaner arrives at the agreed time. Pay securely after the job.' },
    ],
    faqs: [
      { q: 'Do I need to provide cleaning supplies?', a: 'Most cleaners bring their own eco-friendly supplies. You can specify your preferences when booking.' },
      { q: 'What if I\'m not happy with the result?', a: 'Contact us within 24 hours and we\'ll arrange a free re-clean or full refund.' },
      { q: 'Can I book a regular cleaner?', a: 'Yes — you can set up weekly, fortnightly, or monthly recurring bookings at a discounted rate.' },
      { q: 'Are the cleaners insured?', a: 'All verified helpers on SkillLink have been ID-checked. We recommend discussing insurance coverage directly with your helper.' },
    ],
    relatedSlugs: ['window-cleaning', 'handyman', 'furniture-assembly'],
  },
  {
    slug: 'moving',
    category: 'Moving',
    title: 'Moving & Relocation',
    headline: 'Move smarter — stress-free, on your schedule',
    subheadline: 'From studio apartments to full house moves, find strong, reliable movers with vans near you.',
    gradient: 'linear-gradient(135deg,#1E3A8A,#38BDF8)',
    accentColor: '#2563EB',
    accentBg: '#EFF6FF',
    emoji: '🚚',
    included: ['Loading & unloading furniture', 'Transport in van or truck', 'Furniture disassembly & reassembly', 'Staircase and tight-space handling', 'Fragile item wrapping', 'Same-day moves available'],
    priceMin: 800, priceMax: 3000, priceUnit: 'per move',
    steps: [
      { title: 'Share your move details', desc: 'List your pickup and drop-off addresses, inventory size, and preferred date.' },
      { title: 'Get matched with movers', desc: 'See available helpers with vans, reviews, and fixed-price quotes.' },
      { title: 'Move day done', desc: 'Your mover handles everything. You just show up at the new place.' },
    ],
    faqs: [
      { q: 'How far in advance should I book?', a: 'We recommend booking at least 3–5 days ahead, especially for weekends. Same-day bookings are possible for smaller moves.' },
      { q: 'Is my furniture covered if damaged?', a: 'Discuss coverage with your helper before the move. Many carry personal liability insurance.' },
      { q: 'Can helpers disassemble IKEA furniture?', a: 'Yes — most movers on SkillLink are experienced with flat-pack furniture disassembly and reassembly.' },
      { q: 'Do I need to pack boxes myself?', a: 'Packing is a separate add-on. Let your helper know if you need help packing when booking.' },
    ],
    relatedSlugs: ['furniture-assembly', 'cleaning', 'handyman'],
  },
  {
    slug: 'tutoring',
    category: 'Tutoring',
    title: 'Private Tutoring',
    headline: 'Learn faster with one-on-one expert tutoring',
    subheadline: 'Qualified tutors for all ages and subjects — in-person or online, on your schedule.',
    gradient: 'linear-gradient(135deg,#D97706,#F59E0B)',
    accentColor: '#D97706',
    accentBg: '#FFFBEB',
    emoji: '📚',
    included: ['Maths, science & English', 'Norwegian language support', 'University-level subjects', 'Exam & test preparation', 'Homework help sessions', 'Online or in-person available', 'Progress tracking & reports'],
    priceMin: 300, priceMax: 600, priceUnit: 'per hour',
    steps: [
      { title: 'Tell us your subject & level', desc: 'Share the subject, student\'s age, and any specific goals or exams coming up.' },
      { title: 'Meet your tutor', desc: 'Choose from qualified tutors with proven track records. Read their reviews.' },
      { title: 'Start learning', desc: 'Schedule regular sessions and track progress toward your goals.' },
    ],
    faqs: [
      { q: 'How quickly can I see improvement?', a: 'Most students see measurable improvement within 4–6 sessions when attending consistently.' },
      { q: 'Can sessions be online?', a: 'Yes — all tutors on SkillLink can offer online sessions via video call if preferred.' },
      { q: 'Are tutors qualified?', a: 'Our verified tutors hold relevant degrees or teaching qualifications. Check individual profiles for credentials.' },
      { q: 'Can I switch tutors if it\'s not a good fit?', a: 'Absolutely — just find a new tutor and book a session. No long-term commitment required.' },
    ],
    relatedSlugs: ['music-lessons', 'personal-training', 'kids-care'],
  },
  {
    slug: 'handyman',
    category: 'Handyman',
    title: 'Handyman Services',
    headline: 'Fix it today — no job too small',
    subheadline: 'Shelves, repairs, painting, plumbing fixes — one skilled handyman for everything around the house.',
    gradient: 'linear-gradient(135deg,#7C3AED,#A78BFA)',
    accentColor: '#7C3AED',
    accentBg: '#F5F3FF',
    emoji: '🔧',
    included: ['Shelf & picture hanging', 'Flat-pack furniture assembly', 'Door & lock repairs', 'Minor plumbing fixes', 'Tile grouting & caulking', 'TV mounting', 'Painting & touch-ups'],
    priceMin: 350, priceMax: 800, priceUnit: 'per job',
    steps: [
      { title: 'Describe the job', desc: 'List what needs fixing or installing, and add photos if helpful.' },
      { title: 'Pick a handyman', desc: 'Browse skilled, rated handymen in your area and agree on a price.' },
      { title: 'Job done right', desc: 'Your handyman arrives fully equipped. Pay only when you\'re satisfied.' },
    ],
    faqs: [
      { q: 'Do handymen bring their own tools?', a: 'Yes — all handymen on SkillLink come fully equipped. Just let them know if you have specific tools or materials on-site.' },
      { q: 'Can I get a quote before booking?', a: 'Yes — message the handyman with photos and a description to get a fixed-price quote before confirming.' },
      { q: 'What if the job takes longer than expected?', a: 'Agree on a time estimate upfront. Any extension should be agreed and paid at the same hourly rate.' },
      { q: 'Do you handle electrical work?', a: 'Minor fixture swaps are fine. For licensed electrical work, we recommend a certified electrician.' },
    ],
    relatedSlugs: ['cleaning', 'painting', 'furniture-assembly'],
  },
  {
    slug: 'furniture-assembly',
    category: 'Furniture Assembly',
    title: 'Furniture Assembly',
    headline: 'IKEA? Done in an hour.',
    subheadline: 'Expert flat-pack assembly for IKEA, Jysk, and any other brand — fast, tidy, and guaranteed.',
    gradient: 'linear-gradient(135deg,#0369A1,#38BDF8)',
    accentColor: '#0369A1',
    accentBg: '#F0F9FF',
    emoji: '🪑',
    included: ['IKEA PAX, KALLAX, BILLY & all ranges', 'Jysk, Bolia, and other brands', 'Bed frames & mattress bases', 'Wardrobes & shelving units', 'Desks, chairs & office furniture', 'Outdoor furniture', 'Old furniture disassembly'],
    priceMin: 250, priceMax: 600, priceUnit: 'per session',
    steps: [
      { title: 'List your items', desc: 'Tell us what needs assembling — product names and quantities.' },
      { title: 'Book an assembler', desc: 'Choose a skilled assembler with top ratings. Many offer same-day availability.' },
      { title: 'Sit back', desc: 'Your assembler arrives on time, builds everything, and clears up the packaging.' },
    ],
    faqs: [
      { q: 'Do I need to unbox everything first?', a: 'No — your assembler will unbox, build, and dispose of all packaging for you.' },
      { q: 'What if a part is missing?', a: 'Assemblers can identify missing parts and contact the manufacturer on your behalf. They always have basic hardware spares.' },
      { q: 'How long does IKEA assembly take?', a: 'A wardrobe typically takes 1–2 hours. A full room of flat-pack furniture usually takes 3–4 hours.' },
      { q: 'Can you wall-mount shelves at the same time?', a: 'Yes — most assemblers on SkillLink also do wall mounting and hanging as part of the same visit.' },
    ],
    relatedSlugs: ['handyman', 'moving', 'cleaning'],
  },
  {
    slug: 'gardening',
    category: 'Gardening',
    title: 'Gardening & Lawn Care',
    headline: 'A garden you\'re proud of — without the hard work',
    subheadline: 'From lawn mowing to full garden makeovers, find a trusted gardener near you.',
    gradient: 'linear-gradient(135deg,#15803D,#4ADE80)',
    accentColor: '#15803D',
    accentBg: '#F0FDF4',
    emoji: '🌿',
    included: ['Lawn mowing & edging', 'Hedge trimming', 'Weeding & bed clearing', 'Planting & seeding', 'Leaf blowing & collection', 'Tree pruning (small trees)', 'Garden rubbish removal'],
    priceMin: 400, priceMax: 1200, priceUnit: 'per session',
    steps: [
      { title: 'Describe your garden', desc: 'Tell us the size, what needs doing, and how often.' },
      { title: 'Choose a gardener', desc: 'Browse rated local gardeners and pick a one-off or recurring service.' },
      { title: 'Enjoy your garden', desc: 'Your gardener handles everything, leaving your outdoor space looking its best.' },
    ],
    faqs: [
      { q: 'Do gardeners bring their own equipment?', a: 'Most gardeners bring all necessary tools. Let them know if you have a mower or specific equipment you\'d like them to use.' },
      { q: 'Can I book a regular gardener?', a: 'Yes — set up weekly, fortnightly, or monthly recurring visits.' },
      { q: 'Do you handle large tree work?', a: 'Gardeners handle small pruning and trimming. For large tree removal, a specialist arborist is recommended.' },
      { q: 'What about garden design?', a: 'Some gardeners offer basic design consultations. Check individual profiles for this expertise.' },
    ],
    relatedSlugs: ['snow-removal', 'cleaning', 'handyman'],
  },
  {
    slug: 'it-tech',
    category: 'IT & Tech',
    title: 'IT & Tech Support',
    headline: 'Tech problems? Solved in one visit.',
    subheadline: 'Computer repairs, network setup, smart home installation — plain-language support for any device.',
    gradient: 'linear-gradient(135deg,#0284C7,#38BDF8)',
    accentColor: '#0284C7',
    accentBg: '#F0F9FF',
    emoji: '💻',
    included: ['Slow computer speed-up', 'Virus & malware removal', 'Home Wi-Fi setup & optimisation', 'Smart TV & streaming setup', 'Printer & peripheral configuration', 'Data backup & recovery', 'Smart home device installation'],
    priceMin: 400, priceMax: 900, priceUnit: 'per session',
    steps: [
      { title: 'Describe the issue', desc: 'Tell us what device, what\'s going wrong, and how urgent it is.' },
      { title: 'Book a tech expert', desc: 'Choose from rated IT professionals available for home or remote visits.' },
      { title: 'Problem solved', desc: 'Your tech expert fixes the issue and explains everything in plain language.' },
    ],
    faqs: [
      { q: 'Can support be done remotely?', a: 'Yes — many issues can be resolved remotely via screen-sharing without a home visit.' },
      { q: 'Will my data be safe?', a: 'All tech helpers on SkillLink follow data privacy best practices. We recommend backing up before any repair.' },
      { q: 'Do you support Apple and Windows?', a: 'Yes — our helpers are experienced with both platforms, as well as Android, iOS, and Linux.' },
      { q: 'What if the problem isn\'t fixed?', a: 'You only pay if the problem is resolved. Discuss the scope and guarantee with your tech helper upfront.' },
    ],
    relatedSlugs: ['handyman', 'furniture-assembly', 'moving'],
  },
  {
    slug: 'events',
    category: 'Events',
    title: 'Event Planning & Assistance',
    headline: 'Your perfect event — without the stress',
    subheadline: 'From birthday parties to corporate events, find experienced coordinators and assistants near you.',
    gradient: 'linear-gradient(135deg,#E11D48,#FB7185)',
    accentColor: '#E11D48',
    accentBg: '#FFF1F2',
    emoji: '🎉',
    included: ['Birthday & anniversary parties', 'Corporate events & team days', 'Wedding day coordination', 'Vendor sourcing & management', 'On-the-day event management', 'Setup & teardown', 'Guest list & RSVP management'],
    priceMin: 500, priceMax: 3000, priceUnit: 'per event',
    steps: [
      { title: 'Tell us about your event', desc: 'Share the date, location, number of guests, and your vision.' },
      { title: 'Choose your coordinator', desc: 'Browse experienced event professionals with portfolios and reviews.' },
      { title: 'Enjoy your event', desc: 'Your coordinator handles the details so you can focus on the moments that matter.' },
    ],
    faqs: [
      { q: 'How far in advance should I book?', a: 'For large events, 4–6 weeks ahead is ideal. For smaller gatherings, 1–2 weeks is usually fine.' },
      { q: 'Do event helpers bring supplies?', a: 'Some bring decorations and supplies; others coordinate sourcing. Discuss specifics before booking.' },
      { q: 'Can I hire just a day-of coordinator?', a: 'Yes — many helpers specialise in day-of coordination if you\'ve already planned the event yourself.' },
      { q: 'Do you cover outdoor events?', a: 'Absolutely — outdoor events, garden parties, and festival-style events are all catered for.' },
    ],
    relatedSlugs: ['photography', 'cooking', 'cleaning'],
  },
  {
    slug: 'pet-care',
    category: 'Pet Care',
    title: 'Pet Care',
    headline: 'Your pet is in the best hands',
    subheadline: 'Dog walking, pet sitting, grooming and more — find trusted pet carers near you.',
    gradient: 'linear-gradient(135deg,#F97316,#FB923C)',
    accentColor: '#F97316',
    accentBg: '#FFF7ED',
    emoji: '🐾',
    included: ['Dog walking (solo or group)', 'Pet sitting at your home', 'Overnight pet boarding', 'Cat feeding & check-ins', 'Puppy & kitten care', 'Basic grooming', 'Post-walk reports & photos'],
    priceMin: 200, priceMax: 600, priceUnit: 'per session',
    steps: [
      { title: 'Tell us about your pet', desc: 'Share breed, age, temperament, and any special care requirements.' },
      { title: 'Meet your carer', desc: 'Choose a rated, animal-loving carer near you. Many offer a free meet-and-greet.' },
      { title: 'Peace of mind', desc: 'Your pet gets great care. Many carers send photos and updates during the session.' },
    ],
    faqs: [
      { q: 'Are carers experienced with large dogs?', a: 'Yes — filter by breed experience on each carer\'s profile. Many specialise in large or energetic breeds.' },
      { q: 'Can carers handle multiple pets?', a: 'Many carers are comfortable with multiple pets. Mention all your pets when booking.' },
      { q: 'What if my pet has medical needs?', a: 'Note any medication or health conditions in your booking. Some carers have first-aid training.' },
      { q: 'Is there a meet-and-greet before the first visit?', a: 'We strongly recommend a short meet-and-greet so your pet can get comfortable with the carer.' },
    ],
    relatedSlugs: ['dog-walking', 'elder-care', 'kids-care'],
  },
  {
    slug: 'dog-walking',
    category: 'Dog Walking',
    title: 'Dog Walking',
    headline: 'Happy dogs, happy owners',
    subheadline: 'Trusted, insured dog walkers near you — solo or group walks, daily or as needed.',
    gradient: 'linear-gradient(135deg,#B45309,#F59E0B)',
    accentColor: '#B45309',
    accentBg: '#FFFBEB',
    emoji: '🐕',
    included: ['30 or 60-minute walks', 'Solo or small-group walks', 'GPS-tracked routes available', 'Post-walk report & photos', 'Fresh water & treat check', 'Flexible scheduling', 'Regular or one-off bookings'],
    priceMin: 150, priceMax: 350, priceUnit: 'per walk',
    steps: [
      { title: 'Set your schedule', desc: 'Choose walk length, frequency, and preferred times.' },
      { title: 'Match with a walker', desc: 'Find a nearby, experienced dog walker with strong reviews.' },
      { title: 'Walks sorted', desc: 'Your walker picks up and returns your dog, with a post-walk update.' },
    ],
    faqs: [
      { q: 'How many dogs are walked together?', a: 'Most walkers keep groups to 3–4 dogs maximum. Solo walks are available at a slightly higher rate.' },
      { q: 'What happens in bad weather?', a: 'Walkers continue in light rain with appropriate gear. In severe weather, they\'ll contact you to discuss options.' },
      { q: 'Do I need to be home?', a: 'Not at all — many owners set up key arrangements or use a lockbox for their walker.' },
      { q: 'Are walkers insured?', a: 'Recommend verifying insurance directly with your walker. Verified helpers have been ID-checked.' },
    ],
    relatedSlugs: ['pet-care', 'elder-care', 'kids-care'],
  },
  {
    slug: 'snow-removal',
    category: 'Snow Removal',
    title: 'Snow Removal',
    headline: 'Clear paths, safe driveways — every winter morning',
    subheadline: 'Book reliable snow clearing for your home, driveway, or business before the season hits.',
    gradient: 'linear-gradient(135deg,#0369A1,#7DD3FC)',
    accentColor: '#0369A1',
    accentBg: '#F0F9FF',
    emoji: '❄️',
    included: ['Driveway & path clearing', 'Roof snow removal', 'Ice salting & gritting', 'Seasonal contracts available', 'Emergency same-day clearing', 'Commercial properties', 'Staircase clearing'],
    priceMin: 300, priceMax: 800, priceUnit: 'per visit',
    steps: [
      { title: 'Describe your property', desc: 'Tell us the size of your driveway, paths, and any special access needs.' },
      { title: 'Book ahead of winter', desc: 'Secure a reliable snow remover before demand peaks. Seasonal contracts save money.' },
      { title: 'Stay safe all winter', desc: 'Your helper arrives after each snowfall, keeping your property safe and accessible.' },
    ],
    faqs: [
      { q: 'Can I book a seasonal contract?', a: 'Yes — many helpers offer fixed-price seasonal contracts covering all snowfall events through winter.' },
      { q: 'How quickly do they arrive after snowfall?', a: 'Typical response time is 2–4 hours after significant snowfall. Emergency same-day service is available.' },
      { q: 'Do they bring their own equipment?', a: 'Yes — helpers bring snow blowers, shovels, and salt/grit as needed.' },
      { q: 'Do you clear roofs?', a: 'Yes — roof clearing is available but priced separately. Mention it when booking.' },
    ],
    relatedSlugs: ['gardening', 'handyman', 'cleaning'],
  },
  {
    slug: 'cooking',
    category: 'Cooking',
    title: 'Personal Chef & Cooking',
    headline: 'Restaurant-quality meals in your own kitchen',
    subheadline: 'Personal chefs for dinner parties, meal prep, special diets, and weekly home cooking.',
    gradient: 'linear-gradient(135deg,#DC2626,#F87171)',
    accentColor: '#DC2626',
    accentBg: '#FEF2F2',
    emoji: '👨‍🍳',
    included: ['Dinner party cooking (2–20 guests)', 'Weekly meal prep & batch cooking', 'Special dietary menus (vegan, gluten-free, etc.)', 'Kitchen clean-up after cooking', 'Ingredient shopping (add-on)', 'Cooking lessons available', 'Special occasion menus'],
    priceMin: 600, priceMax: 2000, priceUnit: 'per session',
    steps: [
      { title: 'Share your menu needs', desc: 'Tell us the occasion, number of guests, dietary requirements, and cuisine preferences.' },
      { title: 'Choose your chef', desc: 'Browse experienced chefs with cuisine specialties and reviews.' },
      { title: 'Enjoy the meal', desc: 'Your chef cooks, serves, and cleans up — you just enjoy the food.' },
    ],
    faqs: [
      { q: 'Do chefs bring their own ingredients?', a: 'You can choose — chefs can shop for ingredients (cost reimbursed) or work with what you provide.' },
      { q: 'Can chefs accommodate allergies?', a: 'Yes — always specify allergies clearly. Verified chefs are experienced with dietary restrictions.' },
      { q: 'Is this suitable for dinner parties?', a: 'Absolutely — many chefs specialise in multi-course dinner parties for 4–20 guests.' },
      { q: 'Can I book regular weekly cooking?', a: 'Yes — weekly meal prep is very popular. Book a recurring slot at a discounted rate.' },
    ],
    relatedSlugs: ['events', 'shopping', 'cleaning'],
  },
  {
    slug: 'photography',
    category: 'Photography',
    title: 'Photography',
    headline: 'Moments worth keeping — captured beautifully',
    subheadline: 'Portrait, event, product, and real estate photography. Professional photographers near you.',
    gradient: 'linear-gradient(135deg,#7C3AED,#C084FC)',
    accentColor: '#7C3AED',
    accentBg: '#F5F3FF',
    emoji: '📷',
    included: ['Portrait & family sessions', 'Event & party photography', 'Product & e-commerce shots', 'Real estate & Airbnb photography', 'Edited digital files included', 'Online gallery delivery', 'Rush turnaround available'],
    priceMin: 800, priceMax: 4000, priceUnit: 'per session',
    steps: [
      { title: 'Describe your shoot', desc: 'Tell us the type of photography, date, location, and how many edited images you need.' },
      { title: 'Book your photographer', desc: 'Browse portfolios and reviews to find a style that matches your vision.' },
      { title: 'Receive your photos', desc: 'Edited images delivered via online gallery within the agreed timeframe.' },
    ],
    faqs: [
      { q: 'How long does editing take?', a: 'Standard delivery is 5–7 business days. Rush delivery (24–48h) is available at extra cost.' },
      { q: 'What if the weather is bad?', a: 'Most photographers offer free rescheduling for outdoor shoots affected by poor weather.' },
      { q: 'Do I own the photos?', a: 'Yes — you receive full personal usage rights to all edited images. Commercial usage may require a separate licence.' },
      { q: 'Can I see a portfolio before booking?', a: 'Absolutely — all photographers have portfolios on their profile. Always review before booking.' },
    ],
    relatedSlugs: ['events', 'makeup-artist', 'hair-dresser'],
  },
  {
    slug: 'personal-training',
    category: 'Personal Training',
    title: 'Personal Training',
    headline: 'Your fitness goals — with expert guidance',
    subheadline: 'Certified personal trainers for home, park, or gym sessions. All fitness levels welcome.',
    gradient: 'linear-gradient(135deg,#DC2626,#F97316)',
    accentColor: '#DC2626',
    accentBg: '#FEF2F2',
    emoji: '💪',
    included: ['Personalised workout plans', 'Home, park, or gym sessions', 'Strength, cardio, and flexibility training', 'Nutritional guidance', 'Progress tracking', 'Online sessions available', 'All fitness levels & ages'],
    priceMin: 450, priceMax: 900, priceUnit: 'per session',
    steps: [
      { title: 'Share your fitness goals', desc: 'Tell us your current fitness level, goals, any injuries, and preferred workout style.' },
      { title: 'Choose your trainer', desc: 'Browse certified trainers with specialties in weight loss, strength, sports performance, and more.' },
      { title: 'Start training', desc: 'Your trainer designs a programme and guides you to results, session by session.' },
    ],
    faqs: [
      { q: 'Do I need a gym membership?', a: 'No — sessions can be at your home, local park, or an outdoor space. Trainers bring equipment.' },
      { q: 'How quickly will I see results?', a: 'With consistent sessions and good nutrition, most clients see noticeable results within 4–8 weeks.' },
      { q: 'Are trainers certified?', a: 'Yes — all personal trainers on SkillLink hold recognised certifications (PT, NASM, ACE, or equivalent).' },
      { q: 'Can trainers work with injuries?', a: 'Many trainers specialise in rehabilitation training. Mention any injuries or medical conditions when booking.' },
    ],
    relatedSlugs: ['tutoring', 'elder-care', 'dog-walking'],
  },
  {
    slug: 'window-cleaning',
    category: 'Window Cleaning',
    title: 'Window Cleaning',
    headline: 'Crystal-clear windows, inside and out',
    subheadline: 'Professional window cleaners for homes and businesses. Streak-free results guaranteed.',
    gradient: 'linear-gradient(135deg,#0891B2,#22D3EE)',
    accentColor: '#0891B2',
    accentBg: '#ECFEFF',
    emoji: '🪟',
    included: ['Interior & exterior windows', 'Frames, sills & tracks', 'Streak-free finish guaranteed', 'Conservatories & skylights', 'High-rise & rope access certified options', 'Commercial properties', 'Ladder & pole systems'],
    priceMin: 300, priceMax: 1000, priceUnit: 'per session',
    steps: [
      { title: 'Count your windows', desc: 'Tell us the number of windows, floors, and whether you need inside cleaning too.' },
      { title: 'Book a window cleaner', desc: 'Choose a reliable, rated cleaner — many offer recurring monthly or quarterly visits.' },
      { title: 'Enjoy the view', desc: 'Your cleaner arrives with professional equipment and leaves every pane spotless.' },
    ],
    faqs: [
      { q: 'How often should windows be cleaned?', a: 'For most homes, quarterly cleaning is recommended. High-pollution areas or busy roads may need monthly.' },
      { q: 'Can you clean high windows?', a: 'Yes — many cleaners use water-fed poles for high windows. Rope-access certified helpers are available for very tall buildings.' },
      { q: 'Do you clean conservatories?', a: 'Yes — conservatory cleaning including roof panels is available. Mention this when booking.' },
      { q: 'Do I need to be home?', a: 'Not for exterior cleaning. For interior windows, someone should be home.' },
    ],
    relatedSlugs: ['cleaning', 'handyman', 'gardening'],
  },
  {
    slug: 'painting',
    category: 'Painting',
    title: 'Painting & Decorating',
    headline: 'Fresh walls — transformed in a day',
    subheadline: 'Interior painting, wallpapering, and decorating. Precise, tidy, and fairly priced.',
    gradient: 'linear-gradient(135deg,#4F46E5,#818CF8)',
    accentColor: '#4F46E5',
    accentBg: '#EEF2FF',
    emoji: '🖌️',
    included: ['Interior wall & ceiling painting', 'Wallpapering & feature walls', 'Trim, skirting & door painting', 'Surface preparation & filling', 'Furniture protection', 'Water-based & low-VOC paints available', 'Clean-up included'],
    priceMin: 500, priceMax: 3000, priceUnit: 'per room',
    steps: [
      { title: 'Describe your project', desc: 'Tell us the room size, number of walls, current condition, and your colour choices.' },
      { title: 'Get a quote', desc: 'Message a rated painter for a fixed-price quote based on your specifics.' },
      { title: 'Fresh new look', desc: 'Your painter works neatly, protects your furniture, and leaves everything perfect.' },
    ],
    faqs: [
      { q: 'Do painters bring their own paint?', a: 'Most painters can source paint at trade price. You can also choose your own colour and they\'ll apply it.' },
      { q: 'How long does a room take?', a: 'A standard bedroom takes 1–2 days including preparation and two coats. Larger rooms take longer.' },
      { q: 'Do they move furniture?', a: 'Painters will move light furniture and protect it with dust sheets. Large items should be moved beforehand.' },
      { q: 'Can you match existing paint colours?', a: 'Yes — bring a chip or existing paint tin and most painters can match or suggest close alternatives.' },
    ],
    relatedSlugs: ['handyman', 'cleaning', 'furniture-assembly'],
  },
  {
    slug: 'elder-care',
    category: 'Elder Care',
    title: 'Elder Care & Companionship',
    headline: 'Compassionate care for the people you love',
    subheadline: 'Trusted companions and carers for elderly family members — errands, visits, and daily support.',
    gradient: 'linear-gradient(135deg,#9D174D,#F9A8D4)',
    accentColor: '#9D174D',
    accentBg: '#FDF2F8',
    emoji: '💛',
    included: ['Companionship visits', 'Grocery & errand runs', 'Meal preparation', 'Medication reminders', 'Transport to appointments', 'Light housekeeping', 'Social activities & outings'],
    priceMin: 250, priceMax: 500, priceUnit: 'per hour',
    steps: [
      { title: 'Share your loved one\'s needs', desc: 'Tell us what support is needed — hours per week, specific tasks, and any health considerations.' },
      { title: 'Choose a trusted carer', desc: 'Browse verified, compassionate carers with relevant experience and genuine reviews.' },
      { title: 'Ongoing support', desc: 'Your carer builds a relationship with your loved one, providing reliable, friendly assistance.' },
    ],
    faqs: [
      { q: 'Are carers background-checked?', a: 'All verified helpers on SkillLink have completed identity verification. We recommend also requesting references directly.' },
      { q: 'Can carers drive elderly clients to appointments?', a: 'Many carers offer transport assistance. Check individual profiles for this capability.' },
      { q: 'What if my relative has dementia?', a: 'Some carers specialise in dementia care. Filter by experience and mention this need when booking.' },
      { q: 'Can visits be arranged at short notice?', a: 'Yes — many carers are available for same-day or next-day visits, especially for urgent needs.' },
    ],
    relatedSlugs: ['kids-care', 'cooking', 'shopping'],
  },
  {
    slug: 'kids-care',
    category: 'Kids Care',
    title: 'Childcare & Babysitting',
    headline: 'Safe, fun care for your children',
    subheadline: 'Vetted babysitters and childcarers for evenings, weekends, and regular bookings.',
    gradient: 'linear-gradient(135deg,#CA8A04,#FDE047)',
    accentColor: '#CA8A04',
    accentBg: '#FEFCE8',
    emoji: '👶',
    included: ['Evening babysitting', 'Weekend & holiday care', 'After-school pick-up & care', 'Homework help included', 'Meal preparation for children', 'Activity planning', 'First-aid certified options'],
    priceMin: 180, priceMax: 350, priceUnit: 'per hour',
    steps: [
      { title: 'Tell us about your children', desc: 'Share ages, any special needs, bedtime routines, and what you need covered.' },
      { title: 'Find the right carer', desc: 'Browse experienced childcarers with DBS/background check details and parent reviews.' },
      { title: 'Book with confidence', desc: 'Arrange a quick meet-and-greet, then enjoy your time out knowing your children are safe.' },
    ],
    faqs: [
      { q: 'Are carers background-checked?', a: 'Verified helpers have completed ID verification. We recommend also requesting to see any DBS certificates directly.' },
      { q: 'Can carers handle newborns?', a: 'Some carers specialise in infant care. Filter by experience and mention your baby\'s age when booking.' },
      { q: 'Can I book a trial session first?', a: 'Absolutely — a short trial session is a great way to see how your children respond before committing to regular care.' },
      { q: 'What if my child has special needs?', a: 'Some carers have SEND experience and training. Mention this when booking so we can match you appropriately.' },
    ],
    relatedSlugs: ['tutoring', 'elder-care', 'pet-care'],
  },
  {
    slug: 'music-lessons',
    category: 'Music Lessons',
    title: 'Music Lessons',
    headline: 'Learn an instrument — at your own pace',
    subheadline: 'Private music teachers for guitar, piano, singing, violin, and more. All ages and levels.',
    gradient: 'linear-gradient(135deg,#6D28D9,#A78BFA)',
    accentColor: '#6D28D9',
    accentBg: '#F5F3FF',
    emoji: '🎵',
    included: ['Guitar, piano, violin & more', 'Singing & voice training', 'Music theory & reading', 'All ages from 5 to adult', 'Beginner to advanced', 'At-home lessons', 'Exam & grade preparation (ABRSM, RCM)'],
    priceMin: 350, priceMax: 700, priceUnit: 'per hour',
    steps: [
      { title: 'Choose your instrument', desc: 'Tell us which instrument, your current level, and your goals — fun, grades, or performance.' },
      { title: 'Find your teacher', desc: 'Browse qualified music teachers with their own instruments and real student reviews.' },
      { title: 'Start playing', desc: 'Regular sessions at your home, structured around your progress and goals.' },
    ],
    faqs: [
      { q: 'Do I need my own instrument?', a: 'For home lessons you\'ll need the instrument. Some teachers can advise on affordable starter options.' },
      { q: 'What age can children start?', a: 'Most instruments can be started from age 5–6. Some teachers specialise in very young beginners.' },
      { q: 'Can adults learn from scratch?', a: 'Absolutely — many of our most enthusiastic students are adults picking up an instrument for the first time.' },
      { q: 'Are teachers exam-qualified?', a: 'Many hold teaching degrees or music performance qualifications. Check individual profiles for credentials.' },
    ],
    relatedSlugs: ['tutoring', 'kids-care', 'personal-training'],
  },
  {
    slug: 'shopping',
    category: 'Shopping',
    title: 'Personal Shopping & Errands',
    headline: 'Your errands done — so you don\'t have to',
    subheadline: 'Grocery runs, returns, pharmacy pickups — a reliable person to handle your to-do list.',
    gradient: 'linear-gradient(135deg,#8B5CF6,#C084FC)',
    accentColor: '#8B5CF6',
    accentBg: '#F5F3FF',
    emoji: '🛍️',
    included: ['Grocery shopping & delivery', 'Pharmacy & prescription runs', 'Post office & bank errands', 'Returns & exchanges', 'Click & collect pickup', 'Gift shopping & wrapping', 'IKEA & large-store runs'],
    priceMin: 150, priceMax: 400, priceUnit: 'per errand',
    steps: [
      { title: 'List your errands', desc: 'Share your shopping list, stores, budget, and any specific requirements.' },
      { title: 'Book your helper', desc: 'Choose a reliable person near you — many offer same-day availability.' },
      { title: 'Done and delivered', desc: 'Your helper completes your errands and delivers everything to your door.' },
    ],
    faqs: [
      { q: 'How do I pay for the shopping costs?', a: 'You can transfer the estimated amount in advance, or reimburse the helper with receipt upon delivery.' },
      { q: 'Can helpers do multiple errands in one trip?', a: 'Yes — bundle multiple tasks into one booking to save time and cost.' },
      { q: 'Is same-day available?', a: 'Yes — many helpers are available for same-day errands, especially in larger cities.' },
      { q: 'Can they shop at specific stores?', a: 'Yes — specify the stores you need in your booking and your helper will go to those locations.' },
    ],
    relatedSlugs: ['elder-care', 'delivery', 'cooking'],
  },
  {
    slug: 'delivery',
    category: 'Delivery',
    title: 'Delivery & Courier',
    headline: 'Delivered fast — anywhere in your city',
    subheadline: 'Same-day delivery, document courier, and large item transport. Reliable and trackable.',
    gradient: 'linear-gradient(135deg,#EA580C,#FB923C)',
    accentColor: '#EA580C',
    accentBg: '#FFF7ED',
    emoji: '📦',
    included: ['Same-day parcel delivery', 'Document & letter courier', 'Large item transport', 'Airport pickup & drop-off', 'Marketplace item pickup', 'Multi-stop deliveries', 'Evening & weekend available'],
    priceMin: 150, priceMax: 600, priceUnit: 'per delivery',
    steps: [
      { title: 'Share pickup & delivery details', desc: 'Tell us what needs delivering, the addresses, and when it\'s needed.' },
      { title: 'Book a courier', desc: 'Choose a rated courier with the right vehicle for your item size.' },
      { title: 'Delivered on time', desc: 'Your courier picks up and delivers with confirmation at each step.' },
    ],
    faqs: [
      { q: 'Can you deliver large furniture?', a: 'Yes — select a helper with a van when booking large items. Mention dimensions and weight.' },
      { q: 'Is same-day delivery available?', a: 'Yes — same-day bookings are available in most cities, subject to helper availability.' },
      { q: 'Can I track my delivery?', a: 'Your helper will send updates via the SkillLink chat. Real-time GPS tracking coming soon.' },
      { q: 'Are fragile items handled carefully?', a: 'Mention if items are fragile when booking. Most couriers carry basic padding and blankets.' },
    ],
    relatedSlugs: ['shopping', 'moving', 'furniture-assembly'],
  },
  {
    slug: 'makeup-artist',
    category: 'Makeup Artist',
    title: 'Makeup Artist',
    headline: 'Look and feel your best for every occasion',
    subheadline: 'Professional makeup artists for weddings, events, photoshoots, and everyday glam.',
    gradient: 'linear-gradient(135deg,#DB2777,#F9A8D4)',
    accentColor: '#DB2777',
    accentBg: '#FDF2F8',
    emoji: '💄',
    included: ['Bridal & wedding makeup', 'Event & party makeup', 'Editorial & photoshoot makeup', 'Natural & everyday looks', 'Airbrush foundation available', 'Eyebrow shaping', 'Lash application (strip or individual)'],
    priceMin: 600, priceMax: 2500, priceUnit: 'per session',
    steps: [
      { title: 'Tell us your occasion', desc: 'Share the event type, date, your style preferences, and any inspiration images.' },
      { title: 'Choose your artist', desc: 'Browse portfolios and book a trial session before your big day.' },
      { title: 'Get camera-ready', desc: 'Your artist arrives with professional kit and creates a look that lasts all day.' },
    ],
    faqs: [
      { q: 'Should I book a trial before my wedding?', a: 'Yes — we strongly recommend a trial 4–6 weeks before the wedding to finalise your look.' },
      { q: 'Do artists bring their own products?', a: 'Yes — professional artists bring full kits with high-end products. Mention any allergies beforehand.' },
      { q: 'Can artists travel to my venue?', a: 'Most artists offer home or venue visits. A travel fee may apply outside their local area.' },
      { q: 'Can you do makeup for the whole bridal party?', a: 'Yes — book a group session for the whole party. Pricing is per person.' },
    ],
    relatedSlugs: ['hair-dresser', 'photography', 'events'],
  },
  {
    slug: 'hair-dresser',
    category: 'Hair Dresser',
    title: 'Mobile Hairdresser',
    headline: 'Salon quality — in the comfort of your home',
    subheadline: 'Professional mobile hairdressers for cuts, colour, blowouts, and bridal styling.',
    gradient: 'linear-gradient(135deg,#7E22CE,#C084FC)',
    accentColor: '#7E22CE',
    accentBg: '#F3E8FF',
    emoji: '✂️',
    included: ['Haircut & styling', 'Colour & highlights', 'Blowout & blow-dry', 'Bridal & event updo', 'Hair treatments & masks', 'Children\'s haircuts', 'Men\'s cuts & beard trim'],
    priceMin: 400, priceMax: 1500, priceUnit: 'per session',
    steps: [
      { title: 'Describe your hair needs', desc: 'Tell us your hair type, what you\'re after, and any inspiration photos.' },
      { title: 'Book your stylist', desc: 'Choose a qualified mobile stylist with a portfolio and genuine reviews.' },
      { title: 'Salon at home', desc: 'Your stylist arrives with everything they need. No travel, no waiting.' },
    ],
    faqs: [
      { q: 'Do stylists bring their own equipment?', a: 'Yes — all equipment including chair, hair dryer, and products is brought to you.' },
      { q: 'Can you do hair colour at home?', a: 'Yes — most mobile stylists offer colour services. Ensure you have a suitable space with good lighting.' },
      { q: 'Is this more expensive than a salon?', a: 'Prices are comparable to mid-range salons, with the added convenience of no travel or waiting time.' },
      { q: 'Can I book for a bridal party?', a: 'Yes — group bookings for bridal parties are very popular. Book well in advance for weekend dates.' },
    ],
    relatedSlugs: ['makeup-artist', 'photography', 'events'],
  },
  {
    slug: 'car-wash',
    category: 'Car Wash',
    title: 'Mobile Car Wash & Valeting',
    headline: 'Showroom clean — parked right outside your door',
    subheadline: 'Professional mobile car valeting. Interior, exterior, and full detail packages.',
    gradient: 'linear-gradient(135deg,#0EA5E9,#38BDF8)',
    accentColor: '#0EA5E9',
    accentBg: '#F0F9FF',
    emoji: '🚗',
    included: ['Exterior hand wash & dry', 'Interior vacuum & wipe-down', 'Window cleaning (inside & out)', 'Tyre & alloy dressing', 'Dashboard & trim polish', 'Full valet packages', 'Eco waterless options available'],
    priceMin: 300, priceMax: 1200, priceUnit: 'per valet',
    steps: [
      { title: 'Choose your package', desc: 'Select exterior wash, interior clean, or full valet — and tell us about your vehicle.' },
      { title: 'Book a mobile valeter', desc: 'Find a rated valeter near you with their own equipment and water supply.' },
      { title: 'Drive away gleaming', desc: 'Your valeter works at your location while you relax. No queuing, no hassle.' },
    ],
    faqs: [
      { q: 'Do valeters need a water connection?', a: 'Most bring their own water supply. Some use waterless eco products. Confirm when booking.' },
      { q: 'How long does a full valet take?', a: 'A full valet typically takes 2–4 hours depending on vehicle size and condition.' },
      { q: 'Can valeters remove pet hair?', a: 'Yes — pet hair removal is a specialist add-on available from most valeters.' },
      { q: 'Do you do commercial fleets?', a: 'Yes — fleet washing packages are available for businesses. Contact a valeter directly for bulk pricing.' },
    ],
    relatedSlugs: ['handyman', 'delivery', 'cleaning'],
  },
  {
    slug: 'knitting',
    category: 'Knitting',
    title: 'Knitting & Crochet',
    headline: 'Handmade with love — custom knitwear & lessons',
    subheadline: 'Custom knitting commissions and one-on-one knitting or crochet lessons near you.',
    gradient: 'linear-gradient(135deg,#C026D3,#E879F9)',
    accentColor: '#C026D3',
    accentBg: '#FDF4FF',
    emoji: '🧶',
    included: ['Custom knitting commissions', 'Crochet patterns & projects', 'Beginner to advanced lessons', 'Yarn & pattern sourcing advice', 'Repairs & unravelling fixes', 'Children\'s knitwear', 'Seasonal & gift items'],
    priceMin: 200, priceMax: 600, priceUnit: 'per session/item',
    steps: [
      { title: 'Share your project', desc: 'Describe what you\'d like — a commission or lessons — and your skill level.' },
      { title: 'Find your knitter', desc: 'Browse skilled crafters with portfolios of their work.' },
      { title: 'Crafted with care', desc: 'Your item is handmade to your specifications, or your skills grow session by session.' },
    ],
    faqs: [
      { q: 'How long does a custom item take?', a: 'A simple hat takes 2–5 hours. A sweater can take 20–40 hours. Timelines depend on complexity.' },
      { q: 'Can I choose my own yarn?', a: 'Yes — bring your own yarn or ask your knitter to source something specific.' },
      { q: 'Are lessons suitable for complete beginners?', a: 'Yes — most knitters teach complete beginners, starting with casting on and basic stitches.' },
      { q: 'Can you repair damaged knitwear?', a: 'Yes — many helpers offer repair and restoration services for damaged or unravelling knitwear.' },
    ],
    relatedSlugs: ['sewing', 'tutoring', 'kids-care'],
  },
  {
    slug: 'sewing',
    category: 'Sewing',
    title: 'Sewing & Alterations',
    headline: 'Perfectly fitted — expert alterations & repairs',
    subheadline: 'Clothing alterations, repairs, and custom sewing. At-home service or pickup available.',
    gradient: 'linear-gradient(135deg,#0891B2,#67E8F9)',
    accentColor: '#0891B2',
    accentBg: '#ECFEFF',
    emoji: '🪡',
    included: ['Trouser & dress hemming', 'Zip replacement', 'Wedding dress alterations', 'Button replacement & repairs', 'Taking in & letting out garments', 'Custom clothing creation', 'Leather & suede repairs'],
    priceMin: 150, priceMax: 800, priceUnit: 'per item',
    steps: [
      { title: 'Describe what needs altering', desc: 'Tell us the garment, what needs changing, and your timeline.' },
      { title: 'Book your seamstress', desc: 'Choose a skilled sewer near you — many offer home visits or collection.' },
      { title: 'Perfect fit delivered', desc: 'Your garment is returned altered, repaired, and ready to wear.' },
    ],
    faqs: [
      { q: 'How quickly can alterations be done?', a: 'Simple alterations like hemming usually take 1–3 days. More complex work takes longer.' },
      { q: 'Can you alter designer or delicate fabrics?', a: 'Many seamstresses have experience with delicate and designer fabrics. Mention this when booking.' },
      { q: 'Do I need to come for a fitting?', a: 'For tailoring and fitted garments, a fitting is recommended. Many helpers offer home visit fittings.' },
      { q: 'Can you make clothes from scratch?', a: 'Yes — custom dressmaking is available. Provide your measurements and fabric choice, or the helper can source fabric for you.' },
    ],
    relatedSlugs: ['knitting', 'shopping', 'events'],
  },
]

export function getService(slug: string): ServiceDef | undefined {
  return SERVICES.find(s => s.slug === slug)
}

export function getRelatedServices(slugs: string[]): ServiceDef[] {
  return slugs.map(s => SERVICES.find(x => x.slug === s)).filter(Boolean) as ServiceDef[]
}
